# Generated by Django 5.1 on 2024-08-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('apk_file_path', models.FileField(upload_to='media/%Y/%m/%d', verbose_name='apk_file_path')),
                ('first_screenshot_path', models.FileField(upload_to='media/%Y/%m/%d', verbose_name='first_screenshot_path')),
                ('second_screenshot_path', models.FileField(upload_to='media/%Y/%m/%d', verbose_name='second_screenshot_path')),
                ('video_recording_path', models.FileField(upload_to='media/%Y/%m/%d', verbose_name='video_recording_path')),
                ('ui_hierarchy', models.CharField(max_length=255)),
                ('screen_changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL, verbose_name='uploaded_by')),
            ],
        ),
    ]
