# Generated by Django 5.1 on 2024-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='first_screenshot_path',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='first_screenshot_path'),
        ),
        migrations.AlterField(
            model_name='app',
            name='second_screenshot_path',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='second_screenshot_path'),
        ),
        migrations.AlterField(
            model_name='app',
            name='ui_hierarchy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='video_recording_path',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='video_recording_path'),
        ),
    ]
