# Generated by Django 5.1 on 2024-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_app_first_screenshot_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='ui_hierarchy',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
